version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: git_hooks
    versions:
    - 0.6.0
  - dependency-name: ecto
    versions:
    - 3.6.0
